workshops:
  - slug: tdd-2016-10-20
    title: Introduction to test-driven development
    partner:
      name: David Tanzer
      link: http://www.davidtanzer.net/
    location: London, UK
    timestamp: 2016-10-20T09:00:00+0100

  - slug: webops
    title: WebOps
    event: Software Craftsmanship London
    location: London, UK
    timestamp: 2017-10-05T15:15:00+0100
    external:
      text: Try it yourself
      link: https://github.com/SamirTalwar/webops-workshop

talks:
  - slug: smoke--rewriting-a-ruby-project-in-haskell
    title: "Smoke: Rewriting a Ruby project in Haskell for fun and type safety"
    event: HaskellerZ
    location: Zürich, Switzerland
    timestamp: 2020-07-30T19:00:00+0200
    link: https://www.meetup.com/HaskellerZ/events/272048166/
    essay: true
    presentation:
      type: elm
      module: Presentations.SmokeRewritingARubyProjectInHaskell
    video:
      type: youtube
      youtubeId: UdBo9bpjuJ4

  - slug: teaching-a-machine-to-code-2019
    title: Teaching a Machine to Code
    event: Newcrafts 2019
    location: Paris, France
    timestamp: 2019-05-16T10:30:00+0200
    link: https://ncrafts.io/
    essay: true
    presentation:
      type: elm
      module: Presentations.TeachingAMachineToCode2019
    code:
      language: javascript

  - slug: plz-respect-ur-data
    title: Plz, Respect Ur Data
    event: RAPIDS
    location: London, UK
    timestamp: 2018-11-22T19:25:00Z
    essay: true
    presentation:
      type: elm
      module: Presentations.PlzRespectUrData

  - slug: teaching-a-machine-to-code
    title: Teaching a Machine to Code
    event: Joy of Coding 2018
    location: Rotterdam, Netherlands
    timestamp: 2018-06-08T12:00:00+0200
    link: http://joyofcoding.org/2018/
    essay: true
    presentation:
      type: elm
      module: Presentations.TeachingAMachineToCode
    video:
      type: external
      link: https://www.infoq.com/presentations/machine-coding-neural-networks
    code:
      language: javascript

  - title: Driving new features quickly and safely with Elm
    partner:
      name: Nigel Runnels-Moss
      link: https://twitter.com/sleepyfox
    event: TopConf Tallinn
    location: Tallinn, Estonia
    timestamp: 2016-11-17T13:40:00+0200
    link: http://topconf.com/tallinn-2016/

  - title: Staying lean with application logs
    partner:
      name: Nigel Runnels-Moss
      link: https://twitter.com/sleepyfox
    event: TopConf Tallinn
    location: Tallinn, Estonia
    timestamp: 2016-11-17T10:20:00+0200
    link: http://topconf.com/tallinn-2016/

  - slug: 99-problems
    title: I've got 99 problems and asynchronous programming is 127 of them
    event: Codemotion Berlin
    location: Berlin, Germany
    timestamp: 2016-10-24T16:30:00+0200
    link: http://berlin2016.codemotionworld.com/
    essay: true
    presentation:
      type: elm
      module: Presentations.NinetyNineProblems
    code:
      language: javascript

  - slug: staying-lean-with-application-logs
    title: Staying lean with application logs
    event: DevOps Linz
    location: Linz, Austria
    timestamp: 2016-09-22T11:10:00+0200
    link: http://topconf.com/devops-linz-2016/
    essay: true
    presentation:
      type: external
      link: http://www.slideshare.net/SamirTalwar/staying-lean-with-application-logs
    video:
      type: youtube
      youtubeId: 7hOAgE38iz0
    code:
      language: javascript

  - slug: driving-new-features-with-elm
    title: Driving new features quickly and safely with Elm
    event: GeeCon Reactive
    location: Sopot, Poland
    timestamp: 2016-09-09T16:30:00+0200
    link: http://2016.reactive.geecon.org/

  - slug: use-your-type-system
    title: Use Your Type System; Write Less Code
    event: ProgSCon
    location: London, UK
    timestamp: 2015-04-17T15:40:00+0100
    essay: true
    presentation:
      type: external
      link: http://www.slideshare.net/SamirTalwar/use-your-type-system-write-less-code
    video:
      type: youtube
      youtubeId: eut3qeAfD_o
    code:
      language: java

  - slug: design-patterns-in-the-21st-century
    title: Design Patterns in the 21st Century
    event: JAX London
    location: London, UK
    timestamp: 2014-10-15T11:00:00+0100
    essay: true
    presentation:
      type: external
      link: http://www.slideshare.net/SamirTalwar/design-patterns-in-the-21st-century
    video:
      type: external
      link: https://skillsmatter.com/skillscasts/6151-design-patterns-in-the-21st-century
    code:
      language: java

  - slug: highly-strung
    title: Highly Strung
    event: Virtual Java User Group
    timestamp: 2014-07-28T17:00:00+0100
    link: https://virtualjug.com/highly-strung-understanding-your-type-system/
    essay: true
    presentation:
      type: reveal.js
    video:
      type: youtube
      youtubeId: KMnv-A-ANP4
    code:
      language: java
