#!/usr/bin/env zsh

set -e
set -u
set -o pipefail

function stop {
  if [[ -n "${CONTAINER_ID:-}" ]]; then
    docker stop ${CONTAINER_ID}
    docker rm ${CONTAINER_ID}
    CONTAINER_ID=''
  fi
}

make build
CONTAINER_ID=$(
  docker run \
    --name=noodlesandwich.com \
    --detach \
    --interactive \
    --publish=8080:80 \
    --volume=${PWD}/src/nginx.conf:/etc/nginx/conf.d/default.conf \
    --volume=${PWD}/build:/usr/share/nginx/html \
    --volume=${PWD}/assets:/usr/share/nginx/html/assets \
    nginx
)
trap stop EXIT INT TERM
gulp watch
