#!/usr/bin/env zsh

set -e
set -u
set -o pipefail

function stop {
  docker stop noodlesandwich.com
  docker rm noodlesandwich.com
}

make build
docker run \
       --name=noodlesandwich.com \
       --detach \
       --interactive \
       --publish=8080:80 \
       --volume=${PWD}/src/nginx.conf:/etc/nginx/conf.d/default.conf \
       --volume=${PWD}/build:/usr/share/nginx/html \
       --volume=${PWD}/assets:/usr/share/nginx/html/assets \
       nginx
trap stop INT TERM
gulp watch
